config/routes.rb
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                 new_user_confirmation GET    /users/confirmation/new(.:format)                                                        devise/confirmations#new
#                     user_confirmation GET    /users/confirmation(.:format)                                                            devise/confirmations#show
#                                       POST   /users/confirmation(.:format)                                                            devise/confirmations#create
#                              dungeons GET    /dungeons(.:format)                                                                      dungeons#index
#                                       POST   /dungeons(.:format)                                                                      dungeons#create
#                           new_dungeon GET    /dungeons/new(.:format)                                                                  dungeons#new
#                          edit_dungeon GET    /dungeons/:id/edit(.:format)                                                             dungeons#edit
#                               dungeon GET    /dungeons/:id(.:format)                                                                  dungeons#show
#                                       PATCH  /dungeons/:id(.:format)                                                                  dungeons#update
#                                       PUT    /dungeons/:id(.:format)                                                                  dungeons#update
#                                       DELETE /dungeons/:id(.:format)                                                                  dungeons#destroy
#                    challenge_attacked GET    /challenges/:challenge_id/attacked(.:format)                                             challenges/attacked#show
#                            challenges GET    /challenges(.:format)                                                                    challenges#index
#                                       POST   /challenges(.:format)                                                                    challenges#create
#                         new_challenge GET    /challenges/new(.:format)                                                                challenges#new
#                        edit_challenge GET    /challenges/:id/edit(.:format)                                                           challenges#edit
#                             challenge GET    /challenges/:id(.:format)                                                                challenges#show
#                                       PATCH  /challenges/:id(.:format)                                                                challenges#update
#                                       PUT    /challenges/:id(.:format)                                                                challenges#update
#                                       DELETE /challenges/:id(.:format)                                                                challenges#destroy
#                    api_dungeon_levels GET    /api/dungeons/:dungeon_id/levels(.:format)                                               api/dungeons/levels#index {:format=>/json/}
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  root to: 'home#index'

  get 'pages/*id' => 'pages#show', as: :page, format: false

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks',
    }
  resources :users, only: %i[index show] do
    resources :user_auths, param: :provider, only: %i[destroy], controller: 'users/user_auths'
  end

  resources :dungeons
  resources :challenges do
    resource :attacked, only: :show, controller: 'challenges/attacked'
  end
  resources :notifications, only: %i[index update] do
    collection do
      resources :allmarks, only: %i[create], controller: 'notifications/allmarks'
    end
  end
  resources :news

  namespace :api, format: 'json' do

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_user
    ActiveDecorator::Decorator.instance.decorate(super) if super.present?
    super
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_flash.html.slim
-if notice
  input.toggle-checkbox#hidden-checkbox-notice type="checkbox"
  .flash
    p.flash-notice = notice
    label.close-btn for="hidden-checkbox-notice"
- if alert
  input.toggle-checkbox#hidden-checkbox-alert type="checkbox"
  .flash
    p.flash-alert = alert
    label.close-btn for="hidden-checkbox-alert"

app/views/application/_footer.html.slim
footer.footer
  .footer-inner._pc
    small © 2020 HabitDungeon All rights reserved.
  nav.footer-nav._sp
    ul.footer-list
      li.footer-item
        = link_to root_path do
          i.fas.fa-home
          p = "#{user_signed_in? ? 'ホーム' : 'トップ' }"
      li.footer-item
        = link_to dungeons_path do
          i.fas.fa-dungeon
          p ダンジョン
      li.footer-item
        = link_to users_path do
          i.fas.fa-users
          p プレイヤー
      li.footer-item
        = link_to current_user do
          i.fas.fa-user-circle
          p マイページ

app/views/application/_footer_pc.html.slim
footer.footer._pc
  nav.fnav
    ul.fnav-list
      li.fnav-item = link_to 'Twitter', 'https://twitter.com/bbbbruno69'
      li.fnav-item = link_to 'GitHub', 'https://github.com/bbbbruno'
      li.fnav-item = link_to '利用規約', page_path('term-of-use')
      li.fnav-item = link_to 'プライバシーポリシー', page_path('privacy-policy')
      li.fnav-item = link_to 'お問い合わせ', 'https://forms.gle/a7QZbmPjg4wgSSH89', target: :_blank
      li.fnav-item = link_to 'フィードバック', 'https://forms.gle/PPaixKgFoVrmuVs17', target: :_blank
  small © 2020 HabitDungeon All rights reserved.

app/views/application/_footer_sp.html.slim
footer.footer._sp
  nav.fnav
    ul.fnav-list
      li.fnav-item
        = link_to root_path do
          i.fas.fa-home
          p = "#{user_signed_in? ? 'ホーム' : 'トップ' }"
      li.fnav-item
        = link_to dungeons_path do
          i.fas.fa-dungeon
          p ダンジョン
      li.fnav-item
        = link_to users_path do
          i.fas.fa-users
          p プレイヤー
      li.fnav-item
        = link_to current_user do
          i.fas.fa-user-circle
          p マイページ

app/views/application/_hamburger-menu.html.slim
.hamburger-menu._sp
  input#hidden-checkbox-hamburger.nav-unshown type="checkbox"
  label.open for="hidden-checkbox-hamburger"
    span
  label.close for="hidden-checkbox-hamburger"
  nav.hamburger-menu-inner
    .hamburger-menu-top
      = link_to root_path do
        = lazy_image_pack_tag 'logo.png'
      label for="hidden-checkbox-hamburger"
    ul.hamburger-menu-list
      li.hamburger-menu-item
        p HabitDungeon
        = link_to 'ダンジョン', dungeons_path
        = link_to '攻略', challenges_path
        = link_to 'プレイヤー', users_path
      li.hamburger-menu-item
        p ユーザー
        = link_to 'マイページ', current_user
        = link_to '設定', edit_user_registration_path
      li.hamburger-menu-item
        p 運営
        = link_to 'お知らせ', news_index_path
        = link_to 'ヘルプ', page_path('help')
      li.hamburger-menu-item
        p その他
        = link_to 'ログアウト', destroy_user_session_path, method: :delete
      li.hamburger-menu-item
        p リンク
        = link_to 'Twitter', 'https://twitter.com/bbbbruno69'
        = link_to 'GitHub', 'https://github.com/bbbbruno'
        = link_to '利用規約', page_path('term-of-use')
        = link_to 'プライバシーポリシー', page_path('privacy-policy')
        = link_to 'お問い合わせ', 'https://forms.gle/a7QZbmPjg4wgSSH89', target: :_blank
        = link_to 'フィードバック', 'https://forms.gle/PPaixKgFoVrmuVs17', target: :_blank
      small © 2020 HabitDungeon All rights reserved.

app/views/application/_header.html.slim
header.header
  .header-box
    = link_to root_path do
      = lazy_image_pack_tag 'logo.png', class: 'header-logo'
      p.header-tit HabitDungeon

  nav.header-gnav._pc
    ul.header-list
      li.header-item class="#{active_controller?('dungeons') || active_controller_and_action?('challenges', 'index')}"
        = link_to 'ダンジョン', dungeons_path
        ul.header-menu
          li = link_to 'ダンジョン一覧', dungeons_path, class: active_controller_and_action?('dungeons', 'index')
          li = link_to '攻略一覧', challenges_path, class: active_controller_and_action?('challenges', 'index')
      li.header-item class="#{active_controller?('users')}"
        = link_to 'プレイヤー', users_path

  .header-wrap
    - if user_signed_in?
      = render 'notifications'
      / pc
      = render 'toggle-menu'
      / sp
      = render 'hamburger-menu'
    - else
      = link_to '新規登録', new_user_registration_path
      = link_to 'ログイン', new_user_session_path

app/views/application/_notifications.html.slim
.toggle-menu._notifications
  = label_tag 'hidden-checkbox-notificaitons' do
    i.fas.fa-bell
    - if current_user.notifications.unread.exists?
      span.unread = current_user.notifications.unread.count
  input#hidden-checkbox-notificaitons type="checkbox"
  .toggle-menu-content
    label for="hidden-checkbox-notificaitons"
    p.toggle-menu-txt あなたへの通知
    ul.toggle-menu-list._scroll
      - current_user.notifications.includes(sender: { avatar_attachment: :blob }).limit(10).each do |notification|
        li.toggle-menu-item class="#{notification.read? ? '_read' : ''}"
          = link_to notification, method: :patch do
            = lazy_image_tag avatar_url(notification.sender)
            .toggle-menu-message
              p = notification.message
              span = notification.created_at.strftime('%Y/%m/%d')
    .toggle-menu-links
      p = link_to '全ての通知', notifications_path
      p = link_to '全て既読にする', allmarks_path, method: :post

app/views/application/_toggle-menu.slim
.toggle-menu._user._pc
  = label_tag 'hidden-checkbox-user' do
    i.fas.fa-user-circle
  input#hidden-checkbox-user type="checkbox"
  .toggle-menu-content
    label for="hidden-checkbox-user"
    ul.toggle-menu-list
      li.toggle-menu-item._border = link_to 'マイページ', current_user
      li.toggle-menu-item = link_to 'お知らせ', news_index_path
      li.toggle-menu-item._border = link_to 'ヘルプ', page_path('help')
      li.toggle-menu-item._border = link_to 'ユーザー設定', edit_user_registration_path
      li.toggle-menu-item = link_to 'ログアウト', destroy_user_session_path, method: :delete